"use client";
import { useEffect, useState } from "react";
import { Activity, Ban, Check, Gauge, KeyRound, RefreshCw, Server, ShieldCheck } from "lucide-react";
import { api, formatNumber } from "../../lib/api";

export default function SettingsPage() {
  const [data, setData] = useState<any>(); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const load = () => api("/integrations/tiktok").then(setData).catch((e) => setError(e.message));
  useEffect(() => { load(); }, []);
  const readOnly = data?.mode === "READ_ONLY"; const shop = data?.selectedShop ?? data?.shop; const connection = data?.connection; const marketplace = data?.marketplaceRateLimit;
  async function authorize() { setBusy(true); setError(""); try { const result = await api<any>("/integrations/tiktok/authorize", { method: "POST", body: "{}" }); window.location.assign(result.authorizationUrl); } catch (e) { setError(e instanceof Error ? e.message : "Authorization failed"); setBusy(false); } }
  async function select(externalShopId: string) { setBusy(true); try { await api("/integrations/tiktok/shop-selection", { method: "POST", body: JSON.stringify({ externalShopId }) }); await load(); } catch (e) { setError(e instanceof Error ? e.message : "Selection failed"); } setBusy(false); }
  async function refresh() { setBusy(true); try { await api("/integrations/tiktok/refresh", { method: "POST", body: "{}" }); await load(); } catch (e) { setError(e instanceof Error ? e.message : "Refresh failed"); } setBusy(false); }
  return <div className="page"><header className="page-header"><div><span className="eyebrow">TikTok connection</span><h1>{readOnly ? "Real TikTok read-only connection" : "TikTok mock & safety settings"}</h1><p>{readOnly ? "Seller data can be read. No real campaign can freeze, queue, or send." : "Deterministic local provider fixtures remain available for regression testing."}</p></div><span className={`status large ${readOnly ? "read_only" : "mock"}`}>{readOnly ? "REAL TIKTOK — READ ONLY" : "MOCK ONLY"}</span></header>
    {error && <div className="alert error">{error}</div>}
    <section className="settings-hero"><div className="settings-icon"><ShieldCheck/></div><div><h2>Outbound TikTok network requests are physically unavailable</h2><p>The real HTTP client accepts only the verified Phase 2A read operation allowlist.</p>{readOnly && <p><strong>Use a dedicated TikTok developer app for Outreach to isolate its App × Shop API quota from other systems such as order reporting.</strong></p>}</div><div className="gate-list"><span><Check/>No send method in real adapter</span><span><Check/>Mutation paths rejected locally</span><span><Check/>Tokens remain server-side</span></div></section>
    {readOnly && <div className="settings-grid"><section className="panel"><div className="panel-heading"><div><h2>Authorization health</h2><p>{data?.configurationState ?? "Loading"}</p></div><KeyRound/></div><div className="setting-rows"><div><span>Connection state</span><strong>{connection?.status ?? data?.configurationState}</strong></div><div><span>Seller open identity</span><strong>{connection?.sellerOpenId ?? "—"}</strong></div><div><span>Access token expires</span><strong>{connection?.accessTokenExpiresAt ? new Date(connection.accessTokenExpiresAt).toLocaleString() : "—"}</strong></div><div><span>Refresh token expires</span><strong>{connection?.refreshTokenExpiresAt ? new Date(connection.refreshTokenExpiresAt).toLocaleString() : "—"}</strong></div><div><span>Last refresh</span><strong>{connection?.lastRefreshAt ? new Date(connection.lastRefreshAt).toLocaleString() : "Never"}</strong></div><div><span>Refresh failures</span><strong>{formatNumber(connection?.refreshFailureCount)}</strong></div></div><div className="header-actions panel-actions"><button className="button primary" disabled={busy || data?.configurationState === "READ_ONLY_NOT_CONFIGURED"} onClick={authorize}>Authorize seller</button><button className="button secondary" disabled={busy || !connection} onClick={refresh}><RefreshCw size={15}/>Refresh token</button></div></section>
      <section className="panel"><div className="panel-heading"><div><h2>Selected real shop</h2><p>An authorized Indonesian shop must be selected explicitly.</p></div><Server/></div><div className="setting-rows"><div><span>Shop name</span><strong>{shop?.name ?? "Not selected"}</strong></div><div><span>Region</span><strong>{shop?.region ?? "—"}</strong></div><div><span>Shop identifier</span><strong>{shop?.externalShopId ?? "—"}</strong></div><div><span>Last successful API request</span><strong>{connection?.lastApiRequestAt ? new Date(connection.lastApiRequestAt).toLocaleString() : "Never"}</strong></div><div><span>Last request ID</span><strong>{connection?.lastRequestId ?? "—"}</strong></div></div>{data?.authorizedShops?.filter((item: any) => !item.selected).map((item: any) => <button key={item.id} className="button secondary" disabled={busy || item.region !== "ID"} onClick={() => select(item.externalShopId)}>Select {item.name} ({item.region})</button>)}</section></div>}
    {readOnly && <section className="panel"><div className="panel-heading"><div><h2>Read capabilities</h2><p>Authorized-shop access is a Partner Center grant verified by an API read; it is not represented as an invented token scope.</p></div><Activity/></div><div className="setting-rows"><div><span>Authorized shop</span><strong>{connection?.capabilityStatus?.authorizedShop?.available ? "AVAILABLE" : "MISSING / UNVERIFIED"}</strong></div><div><span>Creator Marketplace</span><strong>{connection?.capabilityStatus?.creatorMarketplace?.available ? "AVAILABLE" : "MISSING"}</strong></div><div><span>Affiliate message history</span><strong>{connection?.capabilityStatus?.affiliateMessageHistory?.available ? "AVAILABLE" : "MISSING"}</strong></div><div><span>Refresh state</span><strong>{connection?.refreshState ?? "IDLE"}</strong></div><div><span>Selected-shop currency</span><strong>{shop?.currency ?? "UNKNOWN"} ({shop?.currencyEvidence ?? "not provider-returned"})</strong></div></div><div className="scope-list">{(connection?.grantedScopes ?? []).map((scope: string) => <span className="pill" key={scope}>{scope}</span>)}</div></section>}
    {readOnly && <section className="panel"><div className="panel-heading"><div><h2>Marketplace provider cooldown</h2><p>TikTok quotas are dynamic. The persisted governor spaces reads and blocks local calls during provider cooldown.</p></div><Activity/></div><div className="setting-rows"><div><span>Application mode</span><strong>{data?.mode}</strong></div><div><span>Marketplace scope available</span><strong>{connection?.capabilityStatus?.creatorMarketplace?.available ? "YES" : "NO"}</strong></div><div><span>Last Marketplace success</span><strong>{marketplace?.lastSuccessAt ? new Date(marketplace.lastSuccessAt).toLocaleString() : "Never"}</strong></div><div><span>Last Marketplace 429</span><strong>{marketplace?.last429At ? new Date(marketplace.last429At).toLocaleString() : "Never"}</strong></div><div><span>Current Marketplace cooldown</span><strong>{marketplace?.cooldownActive ? "ACTIVE" : "CLEAR"}</strong></div><div><span>Consecutive Marketplace throttles</span><strong>{formatNumber(marketplace?.consecutiveThrottles ?? 0)}</strong></div><div><span>Next safe attempt</span><strong>{marketplace?.nextSafeAttemptAt ? new Date(marketplace.nextSafeAttemptAt).toLocaleString() : "Now"}</strong></div></div></section>}
    {!readOnly && <div className="settings-grid"><section className="panel"><div className="panel-heading"><div><h2>Effective application ceilings</h2><p>PostgreSQL remains authoritative.</p></div><Gauge/></div><div className="setting-rows"><div><span>Maximum recipients</span><strong>{formatNumber(shop?.maxRecipientsPerCampaign)}</strong></div><div><span>Maximum dispatch attempts</span><strong>{formatNumber(shop?.maxDispatchAttemptsPerCampaign)}</strong></div><div><span>Maximum per shop day</span><strong>{formatNumber(shop?.maxSendsPerDay)}</strong></div><div><span>Dispatch-rate ceiling</span><strong>{formatNumber(shop?.maxDispatchesPerMinute)} / minute</strong></div></div></section><section className="panel"><div className="panel-heading"><div><h2>Mock marketplace</h2><p>All data is local and deterministic.</p></div><Server/></div><div className="setting-rows"><div><span>Market</span><strong>ID</strong></div><div><span>Currency</span><strong>IDR</strong></div><div><span>Page sizes</span><strong>12, 20</strong></div><div><span>Real outbound</span><strong><Ban size={14}/> Unavailable</strong></div></div></section></div>}
  </div>;
}
